cluster.name: sugarcrm54
node.name: sugar1
action.destructive_requires_name: true
cluster.indices.close.enable: false
script.inline: false  
script.stored: false  
script.file: false 
script.update: false
bootstrap.memory_lock: true
#network.host: sugar-elasticsearch54
network.host: _site_
